projectId: "[project-id]"

workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
    replicaCount: 1
    containerSpec:      
      imageUri: "us-docker.pkg.dev/[projectId]/gcr-video-analysis/ad_placement_analysis:latest"

serviceAccount: "ad-placement-service-account@[projectId].iam.gserviceaccount.com"

