workerPoolSpecs:
  - machineSpec:
      machineType: "n1-standard-4"
    replicaCount: 1
    containerSpec:
      imageUri: "us-docker.pkg.dev/lab-project-426319/gcr_video_analysis/ad_placement_analysis:latest"
serviceAccount: "64993516968-compute@developer.gserviceaccount.com"

